name: Mirror SFS denylist
on:
  schedule:
    - cron: '10 3 * * *'         # 03:10 UTC (≈ 05:10 heure FR l'hiver)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug network (headers only)
        shell: bash
        run: |
          set -euxo pipefail
          curl -I https://www.stopforumspam.com || true
          curl -I https://www.stopforumspam.com/downloads/listed_ip_30_all.gz || true
          curl -I https://www.stopforumspam.com/downloads/listed_ip_30_all.md5 || true

      - name: Fetch SFS + verify MD5 (robust)
        shell: bash
        run: |
          set -euo pipefail
          UA="Mozilla/5.0 (GitHub Actions)"
          URL_GZ="https://www.stopforumspam.com/downloads/listed_ip_30_all.gz"
          URL_MD5="https://www.stopforumspam.com/downloads/listed_ip_30_all.md5"

          ok=0
          for i in 1 2 3; do
            # Bust de cache léger côté CDN
            TS=$(date +%s%N)
            curl -fsSL --retry 3 -A "$UA" -o listed_ip_30_all.gz "${URL_GZ}?t=${TS}"
            REMOTE_MD5="$(curl -fsSL --retry 3 -A "$UA" "${URL_MD5}?t=${TS}" | tr -d '\r' | awk '{print $1}')"
            LOCAL_MD5="$(md5sum listed_ip_30_all.gz | awk '{print $1}')"

            echo "REMOTE_MD5=$REMOTE_MD5"
            echo "LOCAL_MD5=$LOCAL_MD5"

            if [[ "$REMOTE_MD5" =~ ^[0-9a-fA-F]{32}$ ]] && [[ "$REMOTE_MD5" == "$LOCAL_MD5" ]]; then
              ok=1; break
            else
              echo "MD5 mismatch (try $i/3) — retrying in 2s..." >&2
              sleep 2
            fi
          done

          if [ "$ok" -ne 1 ]; then
            echo "WARNING: MD5 mismatch after retries — proceeding without strict check." >&2
          fi

          gunzip -f listed_ip_30_all.gz
          mv listed_ip_30_all listed_ip_30_all.txt
          ls -lh listed_ip_30_all.txt


      - name: Commit if changed
        shell: bash
        run: |
          set -euo pipefail
          # Rendez git diff fiable même si le fichier est nouveau
          git add -N listed_ip_30_all.txt
          if ! git diff --quiet -- listed_ip_30_all.txt; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add listed_ip_30_all.txt
            git commit -m "Update SFS list: $(date -u +'%F %T UTC')"
            git push
            echo "Committed new list."
          else
            echo "No change."
          fi
